### ISSUE TITLE
Add stand alone portal practice; no lead up to building the portal

### ISSUE THREAD

**Issue by bdamja** [r0hkx/vine-ssg-practice#21]
Standalone portal practice. So practice just the portal building part, not the leadup

**Comment by r0hkx** [comment]
I'll try to define lead-up to make this easier to close
overworld portal: have ruined portal chest looted and start on the ground next to the portal build spot
nether portal: start with player bridged 6 blocks out

personally I do not feel as if the overworld portal needs a dedicated portal practice with no leadup. I do see this being useful for the nether portal though
