### ISSUE TITLE
Sometimes in the wrong state when switching from nether portal to full nether

### ISSUE THREAD

**Issue by bdamja** [r0hkx/vine-ssg-practice#27]
a

**Comment by r0hkx** [comment]
the player has the wrong state score? looking at the nether/lobby and nether/portal/lobby they seem to both set the player's state score correctly. They are intended to set to different states
```
# state 3 = nether lobby
# state 4 = nether practice

# state 7 = nether portal lobby
# state 8 = nether portal practice
```
