### ISSUE TITLE
add different timer start

### ISSUE THREAD

**Issue by fikiskill** [r0hkx/vine-ssg-practice#45]
add a option that the timer can start on mouse movement or like wasd movement

**Comment by r0hkx** [comment]
this seems unnecessary, care to explain reasoning behind adding this? I would imagine that custom spawn positions (and pitch/yaw of player camera) would fix resolve this as well

**Comment by fikiskill** [comment]
if you move your mouse the slightest bit the timer already starts which is bad for me because sometimes i dont want it to start then. its not like im fully adjusting for something its just a very small movement
