### ISSUE TITLE
add chest practice

### ISSUE THREAD

**Issue by fikiskill** [r0hkx/vine-ssg-practice#46]
add practice for first blacksmith like in the gravel practice map
add practice for 2nd blacksmith with breaking the block and also like in the gravel practice map

**Comment by r0hkx** [comment]
for reference for those not familiar with gravel practice map, does the first blacksmith involve breaking the window and jumping?

**Comment by fikiskill** [comment]
yes. by the gravel practice map i mean that timer starts when you open chest and stops when you close the chest
