### ISSUE TITLE
add ow portal animation practice

### ISSUE THREAD

**Issue by fikiskill** [r0hkx/vine-ssg-practice#49]
add a section where you are in a built ow portal and have 4 seconds to pick up the blocks

**Comment by r0hkx** [comment]
item rng is rampant here, how should that be handled?
should this be a separate mode or an option to add on to existing ow and full ow practice?

**Comment by fikiskill** [comment]
oh yeah the item rng would make it definietly hard to make. maybe just detect if all the common blocks were broken? would require updating when new block breaks are found but idk. Probably an option, the map already adds the load and its always the full 4 seconds so your time wont change

**Comment by bdamja** [comment]
It doesn't seem like this is something people would want to practice that much

**Comment by r0hkx** [comment]
If more people show that they want this mode added, we would be willing to add it, but this does not seem like something anyone wants or needs to practice
